const mongoose = require("mongoose");
const { ObjectID } = require("mongodb");
const Schema = mongoose.Schema;

const playlistSchema = new Schema(
  {
    //id is automatically generated by mongoDB atlas
    author: {
      type: String,
    },

    title: {
      type: String,
    },

    description: {
      type: String,
    },

    playlistImage: {
      type: String, //the link for the image
    },

    //We put posts because the playlist is a collection of the posts which are the songs/music
    posts: [
      {
        id: ObjectID,
        comment: String,
        username: String,
      },
    ],
  },
  { timestamps: true }
);

const Playlist = mongoose.model("Playlist", playlistSchema);

module.exports = Playlist;
