const mongoose = require("mongoose");
const { ObjectID } = require("mongodb");
const Schema = mongoose.Schema;

const userSchema = new Schema(
  {
    //id is automatically generated by mongoDB atlas

    profileImage: {
      type: String,
    },

    firstName: {
      type: String,
      required: true,
    },

    lastName: {
      type: String,
      required: true,
    },

    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
    },

    username: {
      type: String,
      required: true,
    },

    password: {
      type: String,
      required: true,
      minlength: 6,
    },

    posts: [
      {
        id: ObjectID,
        title: String,
        dateCreated: Date,
      },
    ],

    playlists: [
      {
        id: ObjectID,
        playlistName: String,
        dateCreated: Date,
      },
    ],

    followed: [
      {
        id: ObjectID,
        username: String,
      },
    ],

    following: [
      {
        id: ObjectID,
        username: String,
      },
    ],
  },
  { timestamps: true }
);

const User = mongoose.model("User", userSchema);

module.exports = User;
